@startuml


class Partida.EstadoPartida {
- boolean gano
- boolean perdio
- boolean sigueJugando
+ boolean sigueJugando()
+ boolean perdio()
+ boolean gano()
}
class Partida.Partida {
- Jugador jugador
- Mapa mapa
+ void crearPartidaGenerica(Jugador)
+ void comenzar()
+ void terminarTurno()
+ Boolean construir(Defensa)
+ boolean terminarPartida()
+ boolean jugadorTieneTodaLaVidaYMaximosCreditos()
+ void insertarEnemigo(Enemigo)
+ void aplicarDanioEnemigos()
+ boolean jugadorTieneTantosCreditos(int)
+ EstadoPartida estado()
}
@enduml