@startuml

abstract Defensa {
    -danio:int
    -costo:int
    +daniar(parcela:Parcela):void
    +recibirDanio(pieza:Pieza):void
    {abstract}+crearPieza(parcela:Parcela):void
}

class Torre {
    -rango:List<Parcela>
    {static}+Torre(danio, costo, rango, contruccion, parcela)
    +crearPieza(parcela:Parcela):void
    -puedoAtacar():void
}

abstract Contruccion {
    -tiempoDeConstruccion:int
    {abstract} +puedoAtacar():bool
    {abstract} +Reconstruccion():this
}

class Completa {
    +puedoAtacar():bool
    +Reconstruccion():this
}

class Incompleta {
    +puedoAtacar():bool
    +Reconstruccion():this
}

Contruccion <|-- Completa
Contruccion <|-- Incompleta
Defensa <|-- Torre
Torre "1" o-- "1" Contruccion

@enduml